# Generated by Django 3.0.5 on 2020-04-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200407_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emailaddr',
        ),
        migrations.AddField(
            model_name='usermake',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
