# Generated by Django 3.0.5 on 2020-04-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=246)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
